version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:pass@postgres:5432/books
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: books

  redis:
    image: redis:7

  zookeeper:
    image: bitnami/zookeeper:3.8

  kafka:
    image: bitnami/kafka:3.4
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"